development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:6ddd5345b709b725fecbf05e7efa11e4@sole.redistogo.com:9560/
  channel_prefix: stack_show_backend_production
